"""
DICTIONNAIRE EXHAUSTIF ARABE (GUI/DICTIONNAIRES/AR.PY)
"""
DATA_AR = {
    # --- HOME ---
    "titre_app": "ح ي ا ت ي",
    "sous_titre": "مساعدك لامتثال الزكاة والمواريث شرعاً",
    "invitation": "يرجى اختيار وحدة التحليل:",
    "btn_zakat": "🏦  وحدة الفنتك\n(حساب الزكاة الشامل)",
    "btn_heritage": "📜  وحدة الليغالتك\n(تقسيم الميراث)",
    "footer": "منصة حياتي v1.2 — آمنة • دقيقة • متوافقة",
    "selection_langue": "اللغة:",
    "selection_devise": "العملة:",
    "selection_fiqh": "الفقه / المذهب:",
    "err_titre": "خطأ",
    "err_num": "يرجى إدخال أرقام صالحة.",

    # --- ZAKAT MODULE ---
    "zk_titre": "حاسبة الزكاة الشاملة",
    "zk_lbl_cours": "سعر الذهب (جرام واحد):",
    "zk_lbl_cash": "المال النقدي الشخصي:",
    "zk_lbl_bijoux": "قيمة المجوهرات الشخصية:",
    "zk_lbl_stocks": "قيمة البضائع التجارية:",
    "zk_lbl_pro_cash": "سيولة الشركة النقدي:",
    "zk_lbl_dettes": "الديون التجارية قصيرة الأجل:",
    "zk_lbl_recolte": "المحصول الزراعي (كجم):",
    "zk_lbl_elevage": "قطيع الأغنام (رؤوس):",
    "zk_btn_calculer": "احسب الزكاة 💰",
    "zk_rep_titre": "=== تقرير الزكاة الموحد ===",
    "zk_rep_fin": "• 🏦 الأموال والتجارة : تجب الزكاة -> ",
    "zk_rep_fin_non": "• 🏦 الأموال والتجارة : لا تجب الزكاة",
    "zk_rep_agri": "• 🌾 المحاصيل الزراعية : تجب الزكاة -> ",
    "zk_rep_agri_non": "• 🌾 المحاصيل الزراعية : لا شيء",
    "zk_rep_el": "• 🐑 الماشية (الأغنام) : تجب الزكاة -> ",
    "zk_rep_el_non": "• 🐑 الماشية (الأغنام) : لا شيء",
    "zk_unite_kg": " كجم من المحصول",
    "zk_unite_tetes": " رأس / رؤوس",
    "zk_msg_eligible": "الحالة: تجب الزكاة\nالزكاة المستحقة: ",
    "zk_msg_non_eligible": "الحالة: لا تجب الزكاة\n(ثروتك أقل من النصاب).",
    "zk_err_cours": "يجب أن يكون سعر الذهب أكبر من 0.",

    # --- INHERITAGE MODULE ---
    "her_titre": "محرك المواريث العالمي",
    "her_lbl_capital": "صافي التركة المالية:",
    "her_lbl_famille": "الورثة الأحياء المتواجدون:",
    "her_chk_epouse": "الزوجة / الزوجات",
    "her_chk_epoux": "الزوج",
    "her_chk_fils": "الابن",
    "her_chk_fille": "البنت / البنات",
    "her_chk_pere": "الأب",
    "her_chk_mere": "الأم",
    "her_chk_grand_pere": "الجد لأب",
    "her_chk_frere": "الأخ الشقيق",
    "her_chk_frere_ut": "الإخوة لأم",
    "her_chk_oncle": "العم لأب",
    "her_btn_partager": "حساب التقسيم الشرعي ⚖️",
    "her_res_titre": "تقرير توزيع الأنصبة الشرعية",
    "her_lbl_retenus": "الورثة المستحقون فعلياً:",
    "her_lbl_exclus": "الأقارب المحجوبون (حجب حرمان):",
    "her_lbl_exceptions_titre": "❌ الاستبعادات بسبب موانع الإرث الشرعية:",
    "her_lbl_hajb_motif": "محجوب بقريب أقرب منه",
    "her_lbl_indigne_motif": "مستبعد شرعاً (القتل / اختلاف الدين)",
    "her_btn_exceptions": "⚠️ الاستثناءات وموانع الإرث",
    "her_pop_exceptions_titre": "إعدادات موانع الإرث",
    "her_btn_valider": "تأكيد ✅"
}
