"""
DICTIONNAIRE EXHAUSTIF ANGLAIS (GUI/DICTIONNAIRES/EN.PY)
"""
DATA_EN = {
    # --- HOME ---
    "titre_app": "H A Y A A T I",
    "sous_titre": "Your Wealth & Inheritance Compliance Assistant",
    "invitation": "Please select an analysis module:",
    "btn_zakat": "🏦  FINTECH MODULE\n(Full Zakat Calculator)",
    "btn_heritage": "📜  LEGALTECH MODULE\n(Inheritance Sharing)",
    "footer": "Hayaati Platform v1.2 — Secure • Precise • Compliant",
    "selection_langue": "Language:",
    "selection_devise": "Currency:",
    "selection_fiqh": "Fiqh / Madhhab:",
    "err_titre": "Error",
    "err_num": "Please enter valid numbers.",

    # --- ZAKAT MODULE ---
    "zk_titre": "Consolidated Zakat Calculator",
    "zk_lbl_cours": "Gold Price (1g):",
    "zk_lbl_cash": "Personal Cash / Savings:",
    "zk_lbl_bijoux": "Value of Personal Jewelry:",
    "zk_lbl_stocks": "Value of Commercial Stock:",
    "zk_lbl_pro_cash": "Business Cash / Liquidity:",
    "zk_lbl_dettes": "Short-term Business Debts:",
    "zk_lbl_recolte": "Agricultural Harvest (kg):",
    "zk_lbl_elevage": "Sheep/Goat Flock (heads):",
    "zk_btn_calculer": "Calculate Zakat 💰",
    "zk_rep_titre": "=== CONSOLIDATED ZAKAT REPORT ===",
    "zk_rep_fin": "• 🏦 Finance & Commerce : ELIGIBLE -> ",
    "zk_rep_fin_non": "• 🏦 Finance & Commerce : NOT ELIGIBLE",
    "zk_rep_agri": "• 🌾 Agricultural Harvest : DUE -> ",
    "zk_rep_agri_non": "• 🌾 Agricultural Harvest : NONE",
    "zk_rep_el": "• 🐑 Livestock (Sheep) : DUE -> ",
    "zk_rep_el_non": "• 🐑 Livestock (Sheep) : NONE",
    "zk_unite_kg": " kg of harvest",
    "zk_unite_tetes": " head(s)",
    "zk_msg_eligible": "Status: ELIGIBLE\nZakat due: ",
    "zk_msg_non_eligible": "Status: NOT ELIGIBLE\n(Your wealth is below the Nisab).",
    "zk_err_cours": "Gold price must be greater than 0.",

    # --- INHERITAGE MODULE ---
    "her_titre": "Universal Inheritance Engine",
    "her_lbl_capital": "Net Estate Value:",
    "her_lbl_famille": "Living Family Members:",
    "her_chk_epouse": "Wife/Wives",
    "her_chk_epoux": "Husband",
    "her_chk_fils": "Son(s)",
    "her_chk_fille": "Daughter(s)",
    "her_chk_pere": "Father",
    "her_chk_mere": "Mother",
    "her_chk_grand_pere": "Paternal Grandfather",
    "her_chk_frere": "Full Brother(s)",
    "her_chk_frere_ut": "Maternal Siblings",
    "her_chk_oncle": "Paternal Uncles",
    "her_btn_partager": "Calculate Sharing ⚖️",
    "her_res_titre": "Legal Distribution Report",
    "her_lbl_retenus": "Rightful Heirs:",
    "her_lbl_exclus": "Excluded Members (Blocked):",
    "her_lbl_exceptions_titre": "❌ EXCLUSIONS FOR LEGAL EXCEPTIONS:",
    "her_lbl_hajb_motif": "Blocked by closer relative",
    "her_lbl_indigne_motif": "Legal Exclusion (Unworthiness)",
    "her_btn_exceptions": "⚠️ Exceptions / Unworthiness",
    "her_pop_exceptions_titre": "Exception Settings",
    "her_btn_valider": "Validate ✅"
}
