"""
DICTIONNAIRE EXHAUSTIF ESPAGNOL (GUI/DICTIONNAIRES/ES.PY)
"""
DATA_ES = {
    # --- HOME ---
    "titre_app": "H A Y A A T I",
    "sous_titre": "Su Asistente de Cumplimiento Patrimonial y Sucesorio",
    "invitation": "Por favor, seleccione un módulo de análisis:",
    "btn_zakat": "🏦  MÓDULO FINTECH\n(Cálculo Completo de Zakat)",
    "btn_heritage": "📜  MÓDULO LEGALTECH\n(Reparto de Herencia)",
    "footer": "Plataforma Hayaati v1.2 — Segura • Precisa • Conforme",
    "selection_langue": "Idioma:",
    "selection_devise": "Moneda:",
    "selection_fiqh": "Fiqh / Madhhab:",
    "err_titre": "Error",
    "err_num": "Por favor, introduzca números válidos.",

    # --- ZAKAT MODULE ---
    "zk_titre": "Calculadora de Zakat Consolidada",
    "zk_lbl_cours": "Precio del Oro (1g):",
    "zk_lbl_cash": "Dinero en Efectivo Personal:",
    "zk_lbl_bijoux": "Valor de Joyas Personales:",
    "zk_lbl_stocks": "Valor de Mercancías (Comercio):",
    "zk_lbl_pro_cash": "Liquidez de la Empresa:",
    "zk_lbl_dettes": "Deudas Comerciales a Corto Plazo:",
    "zk_lbl_recolte": "Cosecha Agrícola (en kg):",
    "zk_lbl_elevage": "Rebaño de Ovejas (cabezas):",
    "zk_btn_calculer": "Calcular Zakat 💰",
    "zk_rep_titre": "=== REPORTE CONSOLIDADO DE ZAKAT ===",
    "zk_rep_fin": "• 🏦 Finanzas y Comercio : ELEGIBLE -> ",
    "zk_rep_fin_non": "• 🏦 Finanzas y Comercio : NO ELEGIBLE",
    "zk_rep_agri": "• 🌾 Cosecha Agrícola     : DEBIDO -> ",
    "zk_rep_agri_non": "• 🌾 Cosecha Agrícola     : NINGUNA",
    "zk_rep_el": "• 🐑 Ganadería (Ovejas)   : DEBIDO -> ",
    "zk_rep_el_non": "• 🐑 Ganadería (Ovejas)   : NINGUNA",
    "zk_unite_kg": " kg de cosecha",
    "zk_unite_tetes": " cabeza(s)",
    "zk_msg_eligible": "Estado: ELEGIBLE\nZakat debido: ",
    "zk_msg_non_eligible": "Estado: NO ELEGIBLE\n(Su patrimonio está por debajo del Nisab).",
    "zk_err_cours": "El precio del oro debe ser mayor que 0.",

    # --- INHERITAGE MODULE ---
    "her_titre": "Motor de Sucesiones Universal",
    "her_lbl_capital": "Masa Hereditaria Neta:",
    "her_lbl_famille": "Miembros Familiares Vivos:",
    "her_chk_epouse": "Esposa(s)",
    "her_chk_epoux": "Esposo",
    "her_chk_fils": "Hijo",
    "her_chk_fille": "Hija(s)",
    "her_chk_pere": "Padre",
    "her_chk_mere": "Madre",
    "her_chk_grand_pere": "Abuelo Paterno",
    "her_chk_frere": "Hermano(s) Germano(s)",
    "her_chk_frere_ut": "Hermanos Maternos",
    "her_chk_oncle": "Tíos Paternos",
    "her_btn_partager": "Calcular Reparto ⚖️",
    "her_res_titre": "Informe de Distribución Legal",
    "her_lbl_retenus": "Herederos Legítimos:",
    "her_lbl_exclus": "Miembros Excluidos (Bloqueados):",
    "her_lbl_exceptions_titre": "❌ EXCLUSIONES POR EXCEPCIONES LEGALES:",
    "her_lbl_hajb_motif": "Bloqueado por un familiar más cercano",
    "her_lbl_indigne_motif": "Exclusión legal (Indignidad/Religión)",
    "her_btn_exceptions": "⚠️ Excepciones / Indignidad",
    "her_pop_exceptions_titre": "Ajustes de Excepciones",
    "her_btn_valider": "Validar ✅"
}
