"""
DICTIONNAIRE EXHAUSTIF FRANÇAIS (GUI/DICTIONNAIRES/FR.PY)
"""
DATA_FR = {
    "titre_app": "H A Y A A T I",
    "sous_titre": "Votre Assistant de Conformité Patrimoniale & Successorale",
    "invitation": "Veuillez sélectionner un module d'analyse :",
    "btn_zakat": "🏦  MODULE FINTECH\n(Calcul Complet Zakat)",
    "btn_heritage": "📜  MODULE LEGALTECH\n(Partage Successoral)",
    "footer": "Plateforme Hayaati v1.2 — Sûre • Précise • Conforme",
    "selection_langue": "Langue :",
    "selection_devise": "Devise :",
    "selection_fiqh": "Fiqh / Madhhab :",
    "err_titre": "Erreur",
    "err_num": "Veuillez entrer des nombres valides.",
    "btn_accueil": "🏠 Accueil",

    # --- IDÉNTITÉ ÉLARGIE ---
    "id_titre": "👤 Informations du Bénéficiaire",
    "id_nom": "Nom :",
    "id_prenom": "Prénom :",
    "id_pays": "Pays :",
    "id_ville": "Ville :",
    "id_tel": "Téléphone :",

    # --- MODULE ZAKAT ---
    "zk_titre": "Calculateur de Zakat Consolidé",
    "zk_lbl_cours": "Cours de l'or (1g) :",
    "zk_lbl_cash": "Argent liquide personnel :",
    "zk_lbl_bijoux": "Valeur des bijoux personnels :",
    "zk_lbl_stocks": "Valeur du stock marchand (Gros) :",
    "zk_lbl_pro_cash": "Liquidités de l'entreprise :",
    "zk_lbl_dettes": "Dettes fournisseurs court terme :",
    "zk_lbl_recolte": "Récolte agricole (en kg) :",
    "zk_lbl_elevage": "Troupeau d'ovins (têtes) :",
    "zk_btn_calculer": "Calculer la Zakat 💰",
    "zk_rep_titre": "=== RAPPORT CONSOLIDÉ DE LA ZAKAT ===",
    "zk_rep_fin": "• 🏦 Financier & Commerce : ÉLIGIBLE -> ",
    "zk_rep_fin_non": "• 🏦 Financier & Commerce : NON ÉLIGIBLE",
    "zk_rep_agri": "• 🌾 Récoltes Agricoles : DUE -> ",
    "zk_rep_agri_non": "• 🌾 Récoltes Agricoles : AUCUNE",
    "zk_rep_el": "• 🐑 Élevage (Ovins) : DUE -> ",
    "zk_rep_el_non": "• 🐑 Élevage (Ovins) : AUCUNE",
    "zk_unite_kg": " kg de récolte",
    "zk_unite_tetes": " mouton(s)",
    "zk_err_cours": "Le cours de l'or doit être supérieur à 0.",

    # --- MODULE HÉRITAGE ---
    "her_titre": "Moteur Successoral Universel",
    "her_lbl_capital": "Masse successorale nette :",
    "her_lbl_famille": "Membres de la famille vivants :",
    "her_chk_epouse": "Épouse(s)",
    "her_chk_epoux": "Époux",
    "her_chk_fils": "Fils",
    "her_chk_fille": "Fille(s)",
    "her_chk_pere": "Père",
    "her_chk_mere": "Mère",
    "her_chk_grand_pere": "Grand-père paternel",
    "her_chk_frere": "Frère(s) Germain(s)",
    "her_chk_frere_ut": "Frères/Sœurs utérins",
    "her_chk_oncle": "Oncles paternels",
    "her_btn_partager": "Calculer le Partage ⚖️",
    "her_res_titre": "Rapport de Ventilation Légale",
    "her_lbl_retenus": "Héritiers retenus :",
    "her_lbl_exclus": "Membres écartés (Bloqués) :",
    "her_lbl_exceptions_titre": "❌ EXCLUSIONS POUR EXCEPTIONS LÉGALES :",
    "her_lbl_hajb_motif": "Bloqué par un proche",
    "her_lbl_indigne_motif": "Exclusion légale (Indignité)",
    "her_btn_exceptions": "⚠️ Exceptions / Indignités",
    "her_pop_exceptions_titre": "Paramètres des Exceptions",
    "her_btn_valider": "Valider ✅"
}
