"""
DICTIONNAIRE EXHAUSTIF HAUSA (GUI/DICTIONNAIRES/HA.PY)
"""
DATA_HA = {
    # --- HOME ---
    "titre_app": "H A Y A A T I",
    "sous_titre": "Mataimakin Ku na Bin Ka'idodin Dukiya da Gado",
    "invitation": "Da fatan za ku zaɓi rukunin bincike:",
    "btn_zakat": "🏦  KAYAN FINTECH\n(Cikakken Lissafin Zakka)",
    "btn_heritage": "📜  KAYAN LEGALTECH\n(Rabon Gado)",
    "footer": "Dandalin Hayaati v1.2 — Amintattu • Daidai • Masu Biyayya",
    "selection_langue": "Harshe:",
    "selection_devise": "Kuɗi:",
    "selection_fiqh": "Fiqh / Madhhab:",
    "err_titre": "Kuskure",
    "err_num": "Da fatan za a shigar da lambobi masu inganci.",

    # --- ZAKAT MODULE ---
    "zk_titre": "Cikakken Lissafin Zakka",
    "zk_lbl_cours": "Farashin Zinare (Gram 1):",
    "zk_lbl_cash": "Kuɗi Na Kanka (Ajiya):",
    "zk_lbl_bijoux": "Darajar Kayan Zinare Na Parure:",
    "zk_lbl_stocks": "Darajar Kayan Kasuwanci:",
    "zk_lbl_pro_cash": "Kuɗaɗen Kamfani (Kasuwanci):",
    "zk_lbl_dettes": "Basussukan Kasuwanci:",
    "zk_lbl_recolte": "Yawan Amfanin Gona (kg):",
    "zk_lbl_elevage": "Garken Tumaki (Dabbobi):",
    "zk_btn_calculer": "Lissafi Zakka 💰",
    "zk_rep_titre": "=== RAHOTON ZAKKA NA TSARI ===",
    "zk_rep_fin": "• 🏦 Kudade & Kasuwanci : YA DOLE -> ",
    "zk_rep_fin_non": "• 🏦 Kudade & Kasuwanci : BAI DOLE BA",
    "zk_rep_agri": "• 🌾 Amfanin Gona : YA DOLE -> ",
    "zk_rep_agri_non": "• 🌾 Amfanin Gona : BABU",
    "zk_rep_el": "• 🐑 Dabbobi (Tumaki) : YA DOLE -> ",
    "zk_rep_el_non": "• 🐑 Dabbobi (Tumaki) : BABU",
    "zk_unite_kg": " kg na amfani",
    "zk_unite_tetes": " dabba(bobi)",
    "zk_msg_eligible": "Matsayi: YA ZAMA DOLE\nZakka da za a biya: ",
    "zk_msg_non_eligible": "Matsayi: BAI ZAMA DOLE BA\n(Dukiyarku tana ƙasa da Nisab).",
    "zk_err_cours": "Farashin zinare dole ne ya kasance sama da 0.",

    # --- INHERITAGE MODULE ---
    "her_titre": "Injin Raba Gado na Duniya",
    "her_lbl_capital": "Jimillar Dukiyar Gado:",
    "her_lbl_famille": "Membobin Dangi Masu Rai:",
    "her_chk_epouse": "Mata / Mata",
    "her_chk_epoux": "Miji",
    "her_chk_fils": "Da (Namiji)",
    "her_chk_fille": "Iya (Mace)",
    "her_chk_pere": "Uba",
    "her_chk_mere": "Uwa",
    "her_chk_grand_pere": "Kaka (Uban Uba)",
    "her_chk_frere": "Wa ko Kanat",
    "her_chk_frere_ut": "Yan uwa ta wurin uwa",
    "her_chk_oncle": "Kawunni",
    "her_btn_partager": "Lissafi Rabon Gado ⚖️",
    "her_res_titre": "Rahoton Rabon Gado na Shari'a",
    "her_lbl_retenus": "Masu Gado Masu Halatta:",
    "her_lbl_exclus": "Membobin da aka Cire (An Toshe):",
    "her_lbl_exceptions_titre": "❌ KORARRAFI SABODA MATSALAR SHARI'A:",
    "her_lbl_hajb_motif": "An toshe shi saboda dangi",
    "her_lbl_indigne_motif": "An cire shi (Laifi / Addini)",
    "her_btn_exceptions": "⚠️ Keɓance-keɓance / Matsaloli",
    "her_pop_exceptions_titre": "Saitunan Keɓance-keɓance",
    "her_btn_valider": "Tabbatar ✅"
}
