"""
DICTIONNAIRE EXHAUSTIF CHINOIS (GUI/DICTIONNAIRES/ZH.PY)
"""
DATA_ZH = {
    # --- HOME ---
    "titre_app": "H A Y A A T I",
    "sous_titre": "您的财富与遗产合规助手",
    "invitation": "请选择分析模块：",
    "btn_zakat": "🏦  金融科技模块\n(天课完整计算器)",
    "btn_heritage": "📜  法律科技模块\n(遗产分配系统)",
    "footer": "Hayaati 平台 v1.2 — 安全 • 精准 • 合规",
    "selection_langue": "语言：",
    "selection_devise": "货币：",
    "selection_fiqh": "法学派别 / 麦兹海布：",
    "err_titre": "错误",
    "err_num": "请输入有效的数字。",

    # --- ZAKAT MODULE ---
    "zk_titre": "天课综合计算器",
    "zk_lbl_cours": "金价 (每克单价):",
    "zk_lbl_cash": "个人现金/储蓄金额:",
    "zk_lbl_bijoux": "个人黄金首饰价值:",
    "zk_lbl_stocks": "商业库存商品总值:",
    "zk_lbl_pro_cash": "公司账户流动资金:",
    "zk_lbl_dettes": "短期供应商债务:",
    "zk_lbl_recolte": "农业收成总重 (公斤):",
    "zk_lbl_elevage": "绵羊/山羊群 (头数):",
    "zk_btn_calculer": "计算天课 💰",
    "zk_rep_titre": "=== 天课综合清算报告 ===",
    "zk_rep_fin": "• 🏦 现金与商业资产 : 符合纳课标准 -> ",
    "zk_rep_fin_non": "• 🏦 现金与商业资产 : 未达纳课标准",
    "zk_rep_agri": "• 🌾 农业收成类天课 : 应纳税额 -> ",
    "zk_rep_agri_non": "• 🌾 农业收成类天课 : 无",
    "zk_rep_el": "• 🐑 牲畜类 (绵羊)   : 应纳税额 -> ",
    "zk_rep_el_non": "• 🐑 牲畜类 (绵羊)   : 无",
    "zk_unite_kg": " 公斤收成",
    "zk_unite_tetes": " 头数",
    "zk_msg_eligible": "状态：符合纳课条件\n应纳天课金额：",
    "zk_msg_non_eligible": "状态：未达纳课标准\n(您的总资产未达到最低金满限额 Nisab)。",
    "zk_err_cours": "黄金克价必须大于 0。",

    # --- INHERITAGE MODULE ---
    "her_titre": "通用遗产分配核心引擎",
    "her_lbl_capital": "净遗产总面值：",
    "her_lbl_famille": "现存法定家庭成员：",
    "her_chk_epouse": "妻子",
    "her_chk_epoux": "丈夫",
    "her_chk_fils": "儿子",
    "her_chk_fille": "女儿",
    "her_chk_pere": "父亲",
    "her_chk_mere": "母亲",
    "her_chk_grand_pere": "祖父",
    "her_chk_frere": "同胞兄弟",
    "her_chk_frere_ut": "同母异父/异母同父兄弟姐妹",
    "her_chk_oncle": "伯叔父",
    "her_btn_partager": "计算遗产分配 ⚖️",
    "her_res_titre": "法理资产清算及分红报告",
    "her_lbl_retenus": "合法合规继承人：",
    "her_lbl_exclus": "被屏蔽/无继承权亲属：",
    "her_lbl_exceptions_titre": "❌ 剥夺继承权法定例外情况：",
    "her_lbl_hajb_motif": "被更近血亲屏蔽 (Hajb)",
    "her_lbl_indigne_motif": "法理剥夺 (犯罪 / 宗教信仰改变)",
    "her_btn_exceptions": "⚠️ 继承权特殊例外设定",
    "her_pop_exceptions_titre": "例外特殊规则设定",
    "her_btn_valider": "确认选择 ✅"
}
