[project]
name = "hayaati-alarm"
version = "0.1.0"
description = "HayaatiAlarm control for Flet"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Dr Aboudourazak AMADOU", email = "aboudourazak@gmail.com" }
]
dependencies = [
    "flet==0.86.5",
]

[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]"
]

[project.urls]
Homepage = "https://amadoufitter.pages.dev/"
Documentation = "https://github.com/dr-aboudourazak/HAYAATI"
Repository = "https://github.com/dr-aboudourazak/HAYAATI"
Issues = "https://github.com/dr-aboudourazak/HAYAATI"

[tool.setuptools.package-data]
"flutter.hayaati_alarm" = ["**/*"]

[tool.setuptools]
package-dir = {"" = "src"}
license-files = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
